name: flutter_crud_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  uuid: ^3.0.7
  file_picker: ^5.5.0
  camera_camera: ^3.0.0
  dropdown_textfield: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  printing: ^5.11.0
  pdf: ^3.10.4
  open_file: ^3.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  pretty_qr_code: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/1024.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
