// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1wUkhhHtrwYfJMI8h_mp3TaMKRFRCmg',
    appId: '1:973070492703:web:35b7917af2996e5da9212a',
    messagingSenderId: '973070492703',
    projectId: 'limapps-a48e8',
    authDomain: 'limapps-a48e8.firebaseapp.com',
    storageBucket: 'limapps-a48e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxalojQSqEq53dMfAENsfb74UK8ZuJG6E',
    appId: '1:973070492703:android:ebdf5c5c6ed91b7da9212a',
    messagingSenderId: '973070492703',
    projectId: 'limapps-a48e8',
    storageBucket: 'limapps-a48e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCooDFDufuUxW3gtG3iA82O6mrugbq27mY',
    appId: '1:973070492703:ios:fda3ffcc726c4f15a9212a',
    messagingSenderId: '973070492703',
    projectId: 'limapps-a48e8',
    storageBucket: 'limapps-a48e8.appspot.com',
    iosBundleId: 'com.example.firebaseLims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCooDFDufuUxW3gtG3iA82O6mrugbq27mY',
    appId: '1:973070492703:ios:3ae798e9050da9efa9212a',
    messagingSenderId: '973070492703',
    projectId: 'limapps-a48e8',
    storageBucket: 'limapps-a48e8.appspot.com',
    iosBundleId: 'com.example.firebaseLims.RunnerTests',
  );
}
