// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQqDYcKZMASD2ZVjtx9ePmA7pqKHSqKQ',
    appId: '1:938616686346:web:72f19d3d4c42c672019cf3',
    messagingSenderId: '938616686346',
    projectId: 'limsappsflutter',
    authDomain: 'limsappsflutter.firebaseapp.com',
    storageBucket: 'limsappsflutter.appspot.com',
    measurementId: 'G-WFYF8RC10X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDopDe-vznC4SukEv0YiS4kJSw-OPbqzxE',
    appId: '1:938616686346:android:3437793ce7d61f7a019cf3',
    messagingSenderId: '938616686346',
    projectId: 'limsappsflutter',
    storageBucket: 'limsappsflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q2dDTBOvaxcBZX0737L9Q7dWrwJo8mk',
    appId: '1:938616686346:ios:5b58d89ec5ed9989019cf3',
    messagingSenderId: '938616686346',
    projectId: 'limsappsflutter',
    storageBucket: 'limsappsflutter.appspot.com',
    iosBundleId: 'com.example.firebaseLims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Q2dDTBOvaxcBZX0737L9Q7dWrwJo8mk',
    appId: '1:938616686346:ios:cd4ca60e7289b992019cf3',
    messagingSenderId: '938616686346',
    projectId: 'limsappsflutter',
    storageBucket: 'limsappsflutter.appspot.com',
    iosBundleId: 'com.example.firebaseLims.RunnerTests',
  );
}
